import XCTest
@testable import CredentialProvider

/// Verifies that the Swift crypto layer (libsodium) produces identical
/// results to the TypeScript crypto layer (@noble/ciphers) using shared
/// test vectors generated by the TypeScript side.
///
/// Test vectors source: packages/core/src/crypto/__tests__/test-vectors.json
class CryptoCompatibilityTests: XCTestCase {

    private let bridge = CryptoBridge()

    // MARK: - XChaCha20-Poly1305 Decrypt

    func testXChaCha20Poly1305Decrypt() throws {
        // From test-vectors.json xchacha20poly1305 section
        let keyHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
        let plaintextHex = "48656c6c6f2c204b65794b65794b657921" // "Hello, KeyKeyKey!"
        let ciphertextHex = "4d4a19d68b055de39f10d12c82e8ca2b6016318aa77a803b"
            + "7bc7c34556789b3fd5b50b140b6e9bf97d55359a0cf1d5554e87725bcda7b918e1"

        let key = Data(hexString: keyHex)!
        let expectedPlaintext = Data(hexString: plaintextHex)!
        let ciphertext = Data(hexString: ciphertextHex)!

        let decrypted = try bridge.decrypt(ciphertext, key: key)

        XCTAssertEqual(decrypted, expectedPlaintext)
        XCTAssertEqual(String(data: decrypted, encoding: .utf8), "Hello, KeyKeyKey!")
    }

    func testXChaCha20Poly1305DecryptFailsWithWrongKey() {
        let ciphertextHex = "4d4a19d68b055de39f10d12c82e8ca2b6016318aa77a803b"
            + "7bc7c34556789b3fd5b50b140b6e9bf97d55359a0cf1d5554e87725bcda7b918e1"
        let wrongKeyHex = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

        let ciphertext = Data(hexString: ciphertextHex)!
        let wrongKey = Data(hexString: wrongKeyHex)!

        XCTAssertThrowsError(try bridge.decrypt(ciphertext, key: wrongKey)) { error in
            XCTAssertTrue(error is CryptoError)
        }
    }

    // MARK: - DEK Unwrap

    func testDEKUnwrap() throws {
        // From test-vectors.json dekUnwrap section
        let kekHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
        let dekHex = "a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
        let wrappedDEKHex = "2e9fc437ba71e16203024864fe2cd30df69da4dcf776431152689c63c159ca8d"
            + "e68b3278ffea566e176ad30eae046adfb9cf52806f1377c3f54e3930b843156920d0e98aaf9d0c04"

        let kek = Data(hexString: kekHex)!
        let expectedDEK = Data(hexString: dekHex)!
        let wrappedDEK = Data(hexString: wrappedDEKHex)!

        let unwrapped = try bridge.unwrapDEK(wrappedDEK, kek: kek)

        XCTAssertEqual(unwrapped, expectedDEK)
        XCTAssertEqual(unwrapped.count, 32)
    }

    func testDEKUnwrapFailsWithWrongKEK() {
        let wrappedDEKHex = "2e9fc437ba71e16203024864fe2cd30df69da4dcf776431152689c63c159ca8d"
            + "e68b3278ffea566e176ad30eae046adfb9cf52806f1377c3f54e3930b843156920d0e98aaf9d0c04"
        let wrongKEKHex = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

        let wrappedDEK = Data(hexString: wrappedDEKHex)!
        let wrongKEK = Data(hexString: wrongKEKHex)!

        XCTAssertThrowsError(try bridge.unwrapDEK(wrappedDEK, kek: wrongKEK)) { error in
            XCTAssertTrue(error is CryptoError)
        }
    }

    // MARK: - Argon2id PIN Derivation

    func testArgon2idPinDerivation() throws {
        // From test-vectors.json argon2idPin section
        let pin = "1234"
        let saltHex = "00112233445566778899aabbccddeeff"
        let derivedKeyHex = "c13a995629afb54a46a6463d6d828616abf2229ce42a7972afcef4235c4d310b"

        let salt = Data(hexString: saltHex)!
        let expectedKey = Data(hexString: derivedKeyHex)!
        let params = Argon2Params(t: 2, m: 19_456, p: 1, dkLen: 32)

        let derived = try bridge.deriveKEK(password: pin, salt: salt, params: params)

        XCTAssertEqual(derived, expectedKey)
        XCTAssertEqual(derived.count, 32)
    }

    // MARK: - Full Credential Decrypt

    func testFullCredentialDecrypt() throws {
        // From test-vectors.json fullCredential section
        let dekHex = "a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
        let encryptedDataBase64 = "I0P/E+MuNwTNPWZwW7/bPJ5OujRYXsew+R17sURI285IlI5DDFRFqe"
            + "GMyvbN/LSdPJdG+ha9VuvSmLskqPzNmTWvsTLCHVEGtxx8skM2Hubm+qkOZV3xNE1W9btxX/7xRW94"
            + "GhAPndv4S4mtdn+rRa+NZZzdMTmVGjov5SRbVHch880ttfxR8SWCuJ/lHGdrb1/YoM6zJ2sYpagzz1"
            + "vmCvyl5sqW/0zZ8lh5H1ii6/pqUgnBQWIZVPnY4DjL96ESZyTT6AHzOYvthfPQ7oZUqiwcs2fOJqsP"
            + "T+jh6pXPrSZSZHDkipoeLZZ3iH09ohHBhVMshkw4M+j8zVP5wx8jdPE/PvsAyuIGlxkUvnFFJwi0T"
            + "M7Tg3DtixVE32vQOoYhXQA0Yc2FuM1TFvVbXD1+fjlHxvYyTp054Svg8M+DZokzsXoThwzcxPwg395"
            + "LAvuEP5SlnA=="
        let expectedJson = "{\"id\":\"550e8400-e29b-41d4-a716-446655440000\","
            + "\"type\":\"credential\",\"name\":\"GitHub\","
            + "\"username\":\"user@example.com\",\"password\":\"s3cret!\","
            + "\"url\":\"https://github.com\","
            + "\"appIdentifiers\":[\"com.github.ios\"],"
            + "\"tags\":[],\"favorite\":false,"
            + "\"createdAt\":\"2026-01-01T00:00:00.000Z\","
            + "\"updatedAt\":\"2026-01-01T00:00:00.000Z\"}"

        let dek = Data(hexString: dekHex)!
        let encrypted = Data(base64Encoded: encryptedDataBase64)!

        let decrypted = try bridge.decrypt(encrypted, key: dek)
        let json = String(data: decrypted, encoding: .utf8)!

        XCTAssertEqual(json, expectedJson)

        // Also verify individual fields by parsing
        let credential = try JSONSerialization.jsonObject(with: decrypted) as! [String: Any]
        XCTAssertEqual(credential["id"] as? String, "550e8400-e29b-41d4-a716-446655440000")
        XCTAssertEqual(credential["type"] as? String, "credential")
        XCTAssertEqual(credential["name"] as? String, "GitHub")
        XCTAssertEqual(credential["username"] as? String, "user@example.com")
        XCTAssertEqual(credential["password"] as? String, "s3cret!")
        XCTAssertEqual(credential["url"] as? String, "https://github.com")
        XCTAssertEqual(credential["appIdentifiers"] as? [String], ["com.github.ios"])
    }
}

// MARK: - Hex String Helper

extension Data {
    /// Initialize Data from a hex string (e.g., "48656c6c6f").
    init?(hexString: String) {
        let len = hexString.count / 2
        var data = Data(capacity: len)
        var index = hexString.startIndex
        for _ in 0 ..< len {
            let nextIndex = hexString.index(index, offsetBy: 2)
            guard let byte = UInt8(hexString[index ..< nextIndex], radix: 16) else { return nil }
            data.append(byte)
            index = nextIndex
        }
        self = data
    }
}
